In [1]:
import pandas as pd
import numpy as np
import random
from tqdm import tqdm
import re
import os
import json
import time

from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from sklearn.model_selection import train_test_split
# from tensorflow.keras.utils import pad_sequences
from keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Model, load_model
from tensorflow.keras import layers

In [12]:

def clean_text(string: str, 
               punctuations = r'''!()-[]{};:'"\,<>./?@#$%^&*_~''',
               stop_words = stopwords.words('english'),
               # porter = PorterStemmer()
               wnl = WordNetLemmatizer()
              ):
    """
    A method to clean text. It removes punctuations, stop words, applies lemmatization.
    """
    # Removing the punctuations
    for x in string.lower(): 
        if x in punctuations: 
            string = string.replace(x, "") 

    # Converting the text to lower
    string = string.lower()

    # Removing stop words
    string = ' '.join([word for word in string.split() if word not in stop_words])

    # stemming/lemmatizing words. That means changing word to its basic format, for example
    # words 'fishing', 'fished', 'fischer' will be changed into a word 'fisch'
    # lemmatization should be better because stemming changes words too much, for example
    # business is changed into busi
    # string = ' '.join([porter.stem(word) for word in string.split()])
    string = ' '.join([wnl.lemmatize(word, pos = "v") for word in string.split()])

    # Cleaning the whitespaces
    string = re.sub(r'\s+', ' ', string).strip()

    return string

def create_training_data(sentences_file,
                         model_folder,
                         word_vec_dim,
                         embed_file_path,
                         max_sen_len = None,
                         create_embedding_file = False
                        ):
    """
    Creating a training and testing datasets x_train and x_test, and embedding matrix.
    
    Argument sentences_file is a path to the file with sentences.
    
    Argument model_folder is a name of a folder where we will save tokenizer which will be needed after model is
    trained to encode new sentences.
    
    Argument word_vec_dim indicates a length of a vector embeddings.
    
    Argument embed_file_path is a path to a file with vector embeddings assigned to words, like 'glove.840B.300d.txt'.
    
    Argument create_embedding_file indicates if we want to create a new, smaller file with word embeddings from
    'glove.840B.300d.txt' such that it contains only words which are present in sentences_file.
    """
    sentences_tables = pd.read_excel(sentences_file).values
    random.shuffle(sentences_tables)
    clean_sentences = np.array([clean_text(sentence) for sentence in sentences_tables[:, 0]])

    tokenizer = Tokenizer()
    tokenizer.fit_on_texts(clean_sentences)

    sequences = tokenizer.texts_to_sequences(clean_sentences)
    if max_sen_len == None:
        max_sen_len = np.max([len(seq) for seq in sequences])
    x = pad_sequences(sequences, maxlen = max_sen_len)

    x_train, x_test = train_test_split(x, test_size = 0.2)
    
    embed_matrix = create_embedding_matrix(
        tokenizer = tokenizer,
        model_folder = model_folder,
        word_vec_dim = word_vec_dim,
        embed_file_path = embed_file_path
    )
    
    with open(os.path.join(model_folder, 'tokenizer.json'), 'w') as file:
        json.dump(tokenizer.to_json(), file)
        
    x_train.to_csv(os.path.join(model_folder, 'x_train.csv'))
    x_test.to_csv(os.path.join(model_folder, 'x_test.csv'))
    embed_matrix.to_csv(os.path.join(model_folder, 'embed_matrix.csv'))
    
    if create_embedding_file:
        create_embedding_file(tokenizer = tokenizer)
        
    return x_train, x_test, embed_matrix


def get_coefs(word, *arr): 
    return word, list(np.asarray(arr, dtype='float'))


def create_embedding_file(tokenizer,
                          embed_file_src = r'model\glove.840B.300d.txt', 
                          embed_file_trg = r'model\model_embeddings.txt'
                         ):
    """
    This function will create an embedding file called embed_file_trg which will contain only those words 
    from embed_file_src which are present in the training dataset (tokenizer.word_index).
    """

    embeddings = dict(get_coefs(*o.split(" ")) for o in open(embed_file_src, errors = 'ignore'))
    with open(embed_file_trg, 'w') as file:
        for word, index in tokenizer.word_index.items():
            word_vector = embeddings[word]
            line = ' '.join(np.concatenate([[word], word_vector]))
            file.write(line + '\n')


def create_embedding_matrix(tokenizer,
                            model_folder,
                            word_vec_dim,
                            embed_file_path,
                           ):
    """
    A function to create an embedding matrix. This is a matrix where each row is a vector representing a word.
    To create that matrix we use a word embedding file which path is equal to embedding_file_path.
    embedding_matrix[row_number] is a vector representation for a word = list(tokenizer.word_index.keys())[row_number - 1]
    First row of embedding_matrix are zeros. This matrix is needed to train a model.
    """
    embeddings = dict(get_coefs(*o.split(" ")) for o in open(embed_file_path, errors = 'ignore'))

    # embedding_matrix[row_number] is a vector representation of a word = self.tokenizer.word_index.keys()[row_number - 1]
    # first row in embedding_matrix is 0
    embedding_matrix = np.zeros((len(tokenizer.word_counts) + 1, word_vec_dim))
    for word, index in tokenizer.word_index.items():
        if index > len(tokenizer.word_counts):
            break
        else:
            try:
                embedding_matrix[index] = embeddings[word]
            except:
                continue

    return embedding_matrix

In [6]:
sentences_file = r'data\sentences_tables.xlsx'
model_folder = 'model'
word_vec_dim = 300
embed_file_path = r'model\model_embeddings.txt'

In [8]:
x_train, x_test, embed_matrix = create_training_data(
    sentences_file = sentences_file,
    model_folder = model_folder,
    word_vec_dim = word_vec_dim,
    embed_file_path = embed_file_path
)

In [9]:
x_train

array([[ 0,  0,  0, ...,  6,  7, 14],
       [ 0,  0,  0, ..., 15,  1,  4],
       [ 0,  0,  0, ..., 27, 12,  1],
       ...,
       [ 0,  0,  0, ..., 19,  8,  1],
       [ 0,  0,  0, ..., 17,  2,  5],
       [ 0,  0,  0, ..., 13,  6,  7]])

In [10]:
embed_matrix

array([[ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
         0.      ],
       [-0.50318 ,  0.27905 , -0.045497, ...,  0.4781  ,  0.13005 ,
        -0.014399],
       [-0.89423 ,  0.39636 ,  0.64359 , ..., -0.15076 ,  0.06987 ,
         0.041258],
       ...,
       [-0.39054 , -0.55117 , -0.073466, ...,  0.34569 ,  0.30918 ,
        -0.32873 ],
       [ 0.049725, -0.48829 , -0.11179 , ...,  0.033829, -0.068756,
        -0.43567 ],
       [ 0.37492 , -0.052425, -0.60094 , ..., -0.36104 , -0.065253,
        -0.1206  ]])

In [11]:
# check if some word doesnt have vector embeddings assigned
for i, row in enumerate(embed_matrix):
    if (row == np.zeros(300)).all():
        print(i)

0


In [8]:
for i, item in enumerate(tokenizer.word_index.items()):
    print(item)
    if i == 5:
        break

('employee', 1)
('cost', 2)
('user', 3)
('office', 4)
('business', 5)
('unit', 6)


In [22]:
class Encoder(Model):
    def __init__(self,
                 embedding_dim,
                 lstm_out_size,
                 batch_size,
                 embed_matrix
                ):
        super().__init__()
        self.lstm_out_size = lstm_out_size
        self.batch_size = batch_size
        self.embedding = layers.Embedding(
            input_dim = embed_matrix.shape[0],
            output_dim = embedding_dim,
            embeddings_initializer = tf.keras.initializers.Constant(embed_matrix),
            trainable = False
        )
        self.lstm = layers.LSTM(
            units = self.lstm_out_size,
            return_sequences = True,
            return_state = True
        )
        
    @tf.function
    def call(self, x, state_h = None, state_c = None):
        # x.shape = (batch_size, max_sen_len)
        # x is a series of numbers which represent words
        # state_h.shape = (batch_size, lstm_out_size)
        
        if state_h == None or state_c == None:
            state_h, state_c = self.initialize_hidden_state()
        
        # make sure that the types are correct
        x = tf.cast(x, tf.float32)
        state_h = tf.cast(state_h, tf.float32)
        state_c = tf.cast(state_c, tf.float32)
        
        x = self.embedding(x)
        # x.shape after embedding = (batch_size, max_sen_len, embedding_dim)
        # output.shape = (batch_size, max_sen_len, lstm_out_size)
        # state_h.shape = (batch_size, lstm_out_size)
        output, state_h, state_c = self.lstm(x, initial_state = [state_h, state_c])
        return output, state_h, state_c
    
    @tf.function
    def initialize_hidden_state(self):
        state_h = tf.zeros((self.batch_size, self.lstm_out_size))
        state_c = tf.zeros((self.batch_size, self.lstm_out_size))
        return state_h, state_c

In [73]:
encoder = Encoder(embedding_dim = 300,
                 lstm_out_size = 10,
                 batch_size = 2,
                 embed_matrix = embed_matrix
                 )

x = np.array([[1, 2], [1, 2]])

with tf.GradientTape() as tape:
    output, state_h, state_c = encoder(x)
    
variables = encoder.trainable_variables
gradients = tape.gradient(output, variables)

In [74]:
gradients

[<tf.Tensor: shape=(300, 40), dtype=float32, numpy=
 array([[ 3.91362980e-02,  1.78501666e-01, -6.65536746e-02, ...,
          2.27576867e-03,  3.06596979e-03, -5.52950427e-03],
        [-2.44583692e-02, -1.00564852e-01,  4.86165360e-02, ...,
          4.39209789e-02,  3.47434767e-02,  3.46905664e-02],
        [ 7.62790767e-03,  1.84747055e-02, -2.33989414e-02, ...,
         -6.68730587e-02, -5.38272634e-02, -4.74490821e-02],
        ...,
        [-4.10167016e-02, -1.71791986e-01,  7.95203224e-02, ...,
          6.06815591e-02,  4.77755107e-02,  4.92389351e-02],
        [-6.89753098e-03, -4.42978255e-02,  3.52535956e-03, ...,
         -5.33669665e-02, -4.33627591e-02, -3.55112329e-02],
        [-7.87226111e-03, -2.61273235e-05,  3.63165438e-02, ...,
          1.47570401e-01,  1.19062632e-01,  1.03082106e-01]], dtype=float32)>,
 <tf.Tensor: shape=(10, 40), dtype=float32, numpy=
 array([[ 6.16146077e-04,  3.51791561e-04, -2.61891261e-03,
         -8.49191158e-04, -2.83790007e-03, -7.8593

In [75]:
output

<tf.Tensor: shape=(2, 2, 10), dtype=float32, numpy=
array([[[-0.04457429, -0.20452513,  0.07552136,  0.0508462 ,
          0.03812613,  0.01973103, -0.12498064,  0.08286092,
          0.05210062,  0.06269614],
        [-0.05648873, -0.13043042,  0.1044731 ,  0.06710292,
          0.10755109,  0.02488116, -0.18320872,  0.2810727 ,
          0.16890085,  0.2183119 ]],

       [[-0.04457429, -0.20452513,  0.07552136,  0.0508462 ,
          0.03812613,  0.01973103, -0.12498064,  0.08286092,
          0.05210062,  0.06269614],
        [-0.05648873, -0.13043042,  0.1044731 ,  0.06710292,
          0.10755109,  0.02488116, -0.18320872,  0.2810727 ,
          0.16890085,  0.2183119 ]]], dtype=float32)>

In [7]:
# version 1 like in Jonathan Hui pdf
class Bahdau_attention(layers.Layer):
    def __init__(self, units = 10):
        super().__init__()
        self.W1 = layers.Dense(units)
        self.W2 = layers.Dense(units)
        self.V = layers.Dense(1)
        
    @tf.function
    def call(self, decoder_hidden, encoder_hidden):
        # decoder_hidden.shape = (batch_size, hidden_size)
        # decoder_hidden_time_axis.shape = (batch_size, 1, hidden_size)
        decoder_hidden_time_axis = tf.expand_dims(decoder_hidden, 1)
        
        # encoder_hidden.shape = (batch_size, max_sen_len, hidden_size)
        # argument for tanh shape = (batch_size, max_sen_len, hidden_size)
        # score.shape = (batch_size, max_sen_len, 1)
        score = self.V(tf.nn.tanh(self.W1(decoder_hidden_time_axis) + self.W2(encoder_hidden)))
        
        # attention_weights.shape = (batch_size, max_sen_len, 1)
        attention_weights = tf.nn.softmax(score, axis = 1)
        
        # context_vector.shape = (batch_size, hidden_size)
        context_vector = attention_weights * encoder_hidden
        context_vector = tf.reduce_sum(context_vector, axis = 1)
        
        return context_vector, attention_weights

In [8]:
# version 2, like in attention explanation pdf
class Bahdau_attention(layers.Layer):
    def __init__(self):
        super().__init__()
        self.dense = layers.Dense(1)
       
    @tf.function
    def call(self, decoder_state_h, encoder_states_h):
        # decoder_state_h.shape = (batch_size, dec_state_size)
        # encoder_states_h.shape = (batch_size, max_sen_len, enc_state_size)
        
        # make sure that the dtypes are correct
        decoder_state_h = tf.cast(decoder_state_h, tf.float32)
        encoder_states_h = tf.cast(encoder_states_h, tf.float32)
        
        # encoder_states_h_flattened.shape = (batch_size * max_sen_len, enc_state_size)
        # encoder_states_h_flattened = tf.reshape(encoder_states_h, [-1, tf.shape(encoder_states_h)[2]])
        encoder_states_h_flattened = tf.reshape(
            encoder_states_h, [
                tf.shape(encoder_states_h)[0] * tf.shape(encoder_states_h)[1], 
                tf.shape(encoder_states_h)[2]
            ]
        )
        batch_size = tf.shape(encoder_states_h)[0]
        max_sen_len = tf.shape(encoder_states_h)[1]
        enc_state_size = tf.shape(encoder_states_h)[2]
        
        context_vector = tf.TensorArray(dtype = tf.float32, size = 0, dynamic_size = True, clear_after_read = False)
        for b in tf.range(batch_size):
            alpha = e = tf.TensorArray(dtype = tf.float32, size = 0, dynamic_size = True, clear_after_read = False)
            for j in tf.range(max_sen_len):
                # x.shape = (dec_state_size + enc_state_size)
                x = tf.concat([decoder_state_h[b], encoder_states_h_flattened[b * max_sen_len + j]], 0)
                # x.shape = (1, dec_state_size + enc_state_size)
                x = tf.expand_dims(x, 0)
                e = e.write(j, tf.math.exp(self.dense(x))[0])

            e_sum = tf.math.reduce_sum(e.stack())
            for j in tf.range(max_sen_len):
                alpha = alpha.write(j, tf.math.divide(e.read(j), e_sum))

            Sum = tf.TensorArray(dtype = tf.float32, size = 0, dynamic_size = True, clear_after_read = False)
            for j in tf.range(max_sen_len):
                Sum = Sum.write(j, alpha.read(j) * encoder_states_h_flattened[b * max_sen_len + j])

            # context_vector_b is a context vector for 1 sample from batch
            context_vector_b = tf.math.reduce_sum(Sum.stack(), axis = 0)
            # context_vector.shape = (batch_size, enc_state_size)
            context_vector = context_vector.write(b, context_vector_b)
        
        return context_vector.stack()

In [128]:
# tf.config.run_functions_eagerly(True)
tf.config.run_functions_eagerly(False)

In [130]:
attention = Bahdau_attention()
decoder_state_h = tf.constant([[1,2], [4,5]])
encoder_states_h = tf.constant([[[1,2,3], [4,5,3]], [[1,2,3], [4,5,3]]])
encoder_states_h_flattened = tf.reshape(encoder_states_h, [tf.shape(encoder_states_h)[0] * tf.shape(encoder_states_h)[1], tf.shape(encoder_states_h)[2]])

with tf.GradientTape() as tape:
    context_vector = attention(decoder_state_h, encoder_states_h)
    
variables = attention.trainable_variables
gradients = tape.gradient(context_vector, variables)

In [131]:
context_vector

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[3.5908003, 4.5908003, 3.       ],
       [3.5908003, 4.5908003, 3.       ]], dtype=float32)>

In [132]:
gradients

[<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
 array([[-1.1920929e-06],
        [-2.1457672e-06],
        [ 4.2406158e+00],
        [ 4.2406149e+00],
        [-3.0994415e-06]], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-1.013279e-06], dtype=float32)>]

In [9]:
class Decoder(Model):
    def __init__(self, vocab_size, embedding_dim, lstm_out_size, embed_matrix):
        super().__init__()
        self.lstm_out_size = lstm_out_size
        self.embedding = layers.Embedding(
            input_dim = embed_matrix.shape[0],
            output_dim = embedding_dim,
            embeddings_initializer = tf.keras.initializers.Constant(embed_matrix),
            trainable = False
        )
        self.lstm = layers.LSTM(
            units = self.lstm_out_size,
            # return_sequences = True,
            return_state = True
        )
        self.dense = layers.Dense(vocab_size)
        self.attention = Bahdau_attention()
        
    @tf.function
    def call(self, x, decoder_state_h, decoder_state_c, encoder_states_h):
        # x.shape = (batch_size, 1)
        # x is a single number for each batch representing a single word
        # encoder_states_h.shape = (batch_size, max_sen_len, enc_state_size)
        # decoder_state_h.shape = (batch_size, lstm_out_size)
        
        # make sure that the types are correct
        x = tf.cast(x, tf.float32)
        decoder_state_h = tf.cast(decoder_state_h, tf.float32)
        decoder_state_c = tf.cast(decoder_state_c, tf.float32)
        encoder_states_h = tf.cast(encoder_states_h, tf.float32)
        
        # context_vector.shape = (batch_size, enc_state_size)
        context_vector = self.attention(decoder_state_h, encoder_states_h)
        # shape of output of embedding layer = (batch_size, 1, embedding_dim)
        x = self.embedding(x)
        # x.shape after concatenation = (batch_size, 1, enc_state_size + embedding_dim)
        x = tf.concat([tf.expand_dims(context_vector, 1), x], axis = 2)
        
        output, state_h, state_c = self.lstm(x, initial_state = [decoder_state_h, decoder_state_c])
        
        # output.shape = (batch_size, vocab_size)
        output = self.dense(output)
        
        return output, state_h, state_c

In [138]:
decoder = Decoder(vocab_size = 100, 
                  embedding_dim = 300, 
                  lstm_out_size = 20, 
                  embed_matrix = embed_matrix
                 )

x = tf.constant([[1], [2]])
decoder_state_h = tf.constant([[i for i in range(20)], [i for i in range(20)]])
decoder_state_c = tf.constant([[i for i in range(20)], [i for i in range(20)]])
encoder_states_h = tf.constant([[[i for i in range(15)], [i for i in range(15)]], [[i for i in range(15)], [i for i in range(15)]]])

with tf.GradientTape() as tape:
    output, state_h, state_c = decoder(x, decoder_state_h, decoder_state_c, encoder_states_h)
    
variables = decoder.trainable_variables
gradients = tape.gradient(output, variables)

In [137]:
output

<tf.Tensor: shape=(2, 100), dtype=float32, numpy=
array([[ 0.15162158, -0.2666756 , -0.08206277,  0.71664655,  0.15774032,
        -0.26463896, -0.02485025, -0.16136312,  0.32311562,  0.31768876,
        -0.38081762, -0.59177405, -0.35685304, -0.5143362 ,  0.37344497,
        -0.51701427,  0.24112938,  0.3559965 , -0.23429905, -0.93242985,
         0.14618877,  0.46973363, -0.7733953 ,  0.16248974,  0.03708994,
        -0.05201417,  0.17080984,  0.08245593, -0.53828734,  0.5289846 ,
        -0.7155414 , -0.2436806 ,  0.09993283, -0.64873123, -0.38315713,
         0.4200229 ,  0.02848363, -0.07834591,  0.26870382,  0.37282366,
        -0.86660933,  0.79235697, -0.47088167,  0.46041852,  0.12979311,
         0.30807993,  0.3242702 , -0.0882818 , -0.298767  ,  0.15185268,
         0.4537142 ,  0.4380744 ,  0.50783145,  0.2062283 ,  0.416616  ,
        -0.24646498, -0.66551596,  0.10805789, -0.4846673 ,  0.11572916,
         0.79025435,  0.10220787,  0.6163452 , -0.22814785, -0.5057447 ,
 

In [139]:
gradients

[<tf.Tensor: shape=(315, 80), dtype=float32, numpy=
 array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 2.05591097e-02,  5.87581750e-03,  4.36880291e-02, ...,
         -5.95262408e-01, -2.95585115e-03, -2.01966166e-01],
        [ 4.11182195e-02,  1.17516350e-02,  8.73760581e-02, ...,
         -1.19052482e+00, -5.91170229e-03, -4.03932333e-01],
        ...,
        [-1.43110575e-02,  1.94085098e-03,  1.16645843e-02, ...,
         -1.73727512e-01, -9.20270628e-04, -6.59215897e-02],
        [-2.49217115e-02, -2.28512537e-04, -4.86101629e-03, ...,
          4.93213274e-02,  1.79062117e-04,  8.75781570e-03],
        [ 4.53935117e-02,  1.55893841e-03,  1.68263167e-02, ...,
         -2.01263383e-01, -8.90372845e-04, -5.50800711e-02]], dtype=float32)>,
 <tf.Tensor: shape=(20, 80), dtype=float32, numpy=
 array([[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000

In [214]:
@tf.function
def train_step(inp, 
               targ, 
               batch_size, 
               encoder, 
               decoder, 
               loss_function, 
               optimizer):
    # inp.shape = targ.shape (batch_size, max_sen_len)
    # enc_state_h.shape = (batch_size, enc_state_size)
    
    # make sure that the types are correct
    inp = tf.cast(inp, tf.float32)
    targ = tf.cast(targ, tf.float32)
    
    batch_loss = 0
    
    with tf.GradientTape() as tape:
        # enc_output.shape = (batch_size, max_sen_len, enc_state_size)
        # enc_state_h.shape = (batch_size, enc_state_size)
        # enc_output, enc_state_h, enc_state_c = encoder(inp, enc_state_h, enc_state_c)
        enc_output, enc_state_h, enc_state_c = encoder(inp)
        dec_state_h = enc_state_h
        dec_state_c = enc_state_c
        
        # dec_input.shape = (batch_size, 1)
        dec_input = tf.expand_dims([0] * batch_size, 1)
        
        for t in range(targ.shape[1]):
            prediction, dec_state_h, dec_state_c, = decoder(dec_input, dec_state_h, dec_state_c, enc_output)
            # real value passed to loss_function needs to have shape (batch_size).
            # It is a number representing a word from tokenizer.word_index. Real value = 0
            # means that there was no word
            batch_loss += loss_function(targ[:, t], prediction)
            dec_input = tf.expand_dims(targ[:, t], 1)
            
    variables = encoder.trainable_variables + decoder.trainable_variables
    gradients = tape.gradient(batch_loss, variables)
    optimizer.apply_gradients(zip(gradients, variables))
    
    return batch_loss

In [11]:
optimizer = tf.keras.optimizers.Adam(learning_rate = 0.001)
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(reduction = 'none')

@tf.function
def loss_function(real, pred):
    mask = tf.math.logical_not(tf.math.equal(real, 0))
    loss = loss_object(real, pred)
    
    mask = tf.cast(mask, dtype = loss.dtype)
    loss *= mask
    
    return tf.reduce_mean(loss)

In [19]:
# real = tf.expand_dims(x_train[:2, 0], 1)
# pred = tf.expand_dims(x_train[:2, 0], 1)

real = tf.constant([2, 0])
pred = tf.constant([[0.0001, 0.00, 0.99], [1, 0, 0]])

real = tf.cast(real, tf.float32)
pred = tf.cast(pred, tf.float32)

loss_object(real, pred)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.0108437e-04, 2.3841855e-07], dtype=float32)>

In [212]:
epochs = 10
batch_size = 20
embedding_dim = 300

inp = tf.constant(x_train)
targ = tf.constant(x_train)

decoder = Decoder(vocab_size = len(tokenizer.word_index.keys()) + 1,
                  embedding_dim = embedding_dim,
                  lstm_out_size = 100,
                  embed_matrix = embed_matrix
                 )

encoder = Encoder(embedding_dim = embedding_dim,
                 lstm_out_size = 100,
                 batch_size = batch_size,
                 embed_matrix = embed_matrix
                 )

In [215]:
for epoch in range(epochs):
    stime = time.time()
    total_loss = 0
    for batch_number in range(len(inp) // batch_size):
        inp_batch = inp[batch_number * batch_size : (batch_number + 1) * batch_size, :]
        targ_batch = targ[batch_number * batch_size : (batch_number + 1) * batch_size, :]
        
        batch_loss = train_step(inp = inp_batch,
                               targ = targ_batch,
                               batch_size = batch_size,
                               encoder = encoder,
                               decoder = decoder,
                               loss_function = loss_function,
                               optimizer = optimizer
                              )
        total_loss += batch_loss
        
        print(f'Batch number: {batch_number}, Loss: {batch_loss / batch_size}, Time per batch: {(time.time() - stime) / (batch_number + 1)}')
        if batch_loss / batch_size < 0.9:
            break
        
    print(f'Epoch: {epoch + 1}, Loss: {total_loss / ((batch_number + 1) * batch_size)}, Time per epoch: {time.time() - stime}\n')
    if batch_loss / batch_size < 0.9:
        break

Batch number: 0, Loss: 2.809325933456421, Time per batch: 14.651074647903442
Batch number: 1, Loss: 2.3995823860168457, Time per batch: 7.627819180488586
Batch number: 2, Loss: 1.65554940700531, Time per batch: 5.285693724950154
Batch number: 3, Loss: 1.7393203973770142, Time per batch: 4.116266667842865
Batch number: 4, Loss: 1.6695903539657593, Time per batch: 3.4108400344848633
Batch number: 5, Loss: 1.410011887550354, Time per batch: 2.9619738260904946
Batch number: 6, Loss: 1.2773363590240479, Time per batch: 2.653951951435634
Batch number: 7, Loss: 1.5331032276153564, Time per batch: 2.4294706284999847
Batch number: 8, Loss: 1.2173337936401367, Time per batch: 2.2571023570166693
Batch number: 9, Loss: 1.4510911703109741, Time per batch: 2.118311882019043
Batch number: 10, Loss: 1.3761066198349, Time per batch: 2.007483720779419
Batch number: 11, Loss: 1.3919532299041748, Time per batch: 1.9165438612302144
Batch number: 12, Loss: 1.5510022640228271, Time per batch: 1.8359561883486

In [199]:
encoder.save('model/encoder')

INFO:tensorflow:Assets written to: model/encoder\assets


INFO:tensorflow:Assets written to: model/encoder\assets


In [200]:
decoder.save('model/decoder')

INFO:tensorflow:Assets written to: model/decoder\assets


INFO:tensorflow:Assets written to: model/decoder\assets


## model testing

In [201]:
encoder = load_model('model/encoder')
decoder = load_model('model/decoder')

In [71]:
tokenizer.word_index.keys()

dict_keys(['employee', 'user', 'cost', 'office', 'business', 'unit', 'center', 'hierarchy', 'productivity', 'type', 'work', 'date', 'region', 'sub', 'timesheet', 'empower', 'email', 'join', 'name', 'activity', 'translate', 'department', 'perform', 'word', 'manager', 'code', 'measure', 'job', 'title', 'operation', 'country', 'currency', 'adress', 'city', 'language', 'helix', 'id', 'group', 'freelancer', 'vendor', 'status', 'client', 'mother', 'tongue', 'capacity'])

In [56]:
def rmse(x, y):
    x = np.array(x)
    y = np.array(y)

    return np.sqrt(np.sum((x - y) ** 2))

In [216]:
sentences = np.array([
    'freelancer department', 'vendor office', 'office region', 'office business unit', 'manager name', 'user name',
    'mother tongue', 'mother language', 'operation type', 'work type'
])

differences = pd.DataFrame()
for sentence1 in sentences:
    for sentence2 in np.delete(sentences, np.where(sentences == sentence1)):
        sequences = tokenizer.texts_to_sequences([sentence1, sentence2])
        x = pad_sequences(sequences, maxlen = 20)

        for i in range(20 - x.shape[0]):
            x = np.concatenate((x, np.zeros((1, 20))))

        encoded_x = encoder(x)[0]
        new_row = pd.DataFrame([[sentence1, sentence2, rmse(encoded_x[0].numpy(), encoded_x[1].numpy())]])
        differences = pd.concat((differences, new_row))
        
differences.columns = ['sentence1', 'sentence2', 'difference']
differences = differences.sort_values(by = 'difference')
differences.reset_index(drop = True, inplace = True)

In [239]:
i = 0

In [244]:
differences.iloc[i * 20 : (i + 1) * 20]

sentence1              sentence2  difference
40         operation type              user name    1.951066
41              user name         operation type    1.951066
42        mother language         operation type    1.980350
43         operation type        mother language    1.980350
44         operation type           manager name    2.036666
45           manager name         operation type    2.036666
46        mother language          vendor office    2.051085
47          vendor office        mother language    2.051085
48          office region           manager name    2.058947
49           manager name          office region    2.058947
50          mother tongue          office region    2.079474
51          office region          mother tongue    2.079474
52              user name  freelancer department    2.113164
53  freelancer department              user name    2.113164
54         operation type  freelancer department    2.117957
55  freelancer department         operation type    2.117957
56          vendor office   office business unit    2.121174
57   office business unit          vendor office    2.121174
58        mother language           manager name    2.213384
59           manager name        mother language    2.213384

In [243]:
i += 1